version: '3'

services:
  pg_db:
    image: postgres
    container_name: pg_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_db_data:\E:\Docker\dockerization\postgres\data
    ports:
      - "5432:5432"
  web:
    depends_on:
      - pg_db
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: testing
    environment:
      - DEBUG=True
      - SERVER=False
      - ALLOWED_HOSTS=*,
      - SQL=False
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=pg_db
      - DB_PORT=5432
    volumes:
      - .:/testing
    ports:
      - "8000:8000"

  pg_admin:
    profiles: ["debug"]
    image: dpage/pgadmin4
    ports:
      - "7000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 1234@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pg_admin_data:\E:\Docker\dockerization\pgadmin
    depends_on:
      - pg_db

volumes:
  pg_db_data:
  pg_admin_data:
  media: